# src/hisavm/errors.py
from __future__ import annotations

ERR_NONE = 0
ERR_ILLEGAL_OPCODE = 1
ERR_ILLEGAL_ENCODING = 2
ERR_ILLEGAL_REG = 3
ERR_ILLEGAL_FLAG = 4
ERR_CONFORMANCE_SETFLAG_REQUIRED = 5

ERR_AUDIT_DERIVED_MISMATCH = 6
ERR_AUDIT_RHO_NEGATIVE = 7
ERR_AUDIT_MOD4 = 8
ERR_AUDIT_EPS_RANGE = 9
