"""
test_witness_hole.py — Proves integrally_closed = false

A monoid M is integrally closed iff M = cone(M) ∩ ℤ^n.
When integrally_closed=false, there exist vectors in cone(M)∩ℤ^n that are
NOT in the monoid generated by the original 28 letter vectors.

The Hilbert basis (38 vectors) includes extra vectors that Normaliz
discovered as "gap fillers". Any of these extra vectors serves as a
*witness hole*: it lies in the cone but is NOT a non-negative integer
combination of the 28 original letter rows.
"""
import os
import sys
import json
import csv
import unittest

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "src"))

from hijaiyyahlang.hb import load_hb_json, is_in_monoid_greedy

# Canonical v18 column names (the 18D identity vector)
V18_COLS = [
    "ThetaHat", "nt", "nf", "nm",
    "km", "kt", "kd", "ka", "kz",
    "qa", "qt", "qd", "qs", "qz",
    "AN", "AK", "AQ",
]
HAMZAH_ALTS = ["hamzah_marker", "hamzah", "varsigma", "epsilon", "eps"]


def load_letter_vectors():
    """Load the 28 original letter vectors from MH-28-v1.0-18D.csv."""
    csv_path = os.path.join(ROOT, "MH-28-v1.0-18D.csv")
    if not os.path.exists(csv_path):
        csv_path = os.path.join(ROOT, "release",
                                "HL-18-v1.0+local.1", "MH-28-v1.0-18D.csv")
    vectors = []
    with open(csv_path, "r", encoding="utf-8-sig") as f:
        r = csv.DictReader(f)
        header = [h.strip() for h in (r.fieldnames or [])]

        # Resolve hamzah column name
        hamzah_col = None
        for alt in HAMZAH_ALTS:
            if alt in header:
                hamzah_col = alt
                break
        if hamzah_col is None:
            raise ValueError(f"No hamzah-marker column found in {header}")

        for row in r:
            v = [int(row[c]) for c in V18_COLS]
            v.append(int(row[hamzah_col]))
            vectors.append(v)
    return vectors


class TestWitnessHole(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        hb_json = os.path.join(ROOT, "release",
                               "HL-18-v1.0+local.1", "artifacts", "HB18.json")
        if not os.path.exists(hb_json):
            hb_json = os.path.join(os.path.dirname(ROOT),
                                   "hl-release-HL-18-v1.0", "artifacts",
                                   "HB18.json")
        cls.hb = load_hb_json(hb_json)
        cls.letter_vectors = load_letter_vectors()

    def test_hilbert_basis_size(self):
        """HB18 must have exactly 38 elements."""
        self.assertEqual(self.hb.hb_size, 38)

    def test_letter_vectors_are_28(self):
        """Original letter set must have exactly 28 vectors."""
        self.assertEqual(len(self.letter_vectors), 28)

    def test_all_letters_in_basis(self):
        """All 28 letter vectors must appear in the Hilbert basis."""
        hb_set = {tuple(v) for v in self.hb.basis}
        for lv in self.letter_vectors:
            self.assertIn(tuple(lv), hb_set,
                          f"Letter vector {lv} missing from HB")

    def test_witness_holes_exist(self):
        """
        integrally_closed = false ⟹ ∃ vectors in HB that are NOT
        non-negative integer combinations of the 28 letter vectors.
        """
        letter_set = {tuple(v) for v in self.letter_vectors}
        extra_vectors = [v for v in self.hb.basis
                         if tuple(v) not in letter_set]
        self.assertGreater(len(extra_vectors), 0,
                           "No extra vectors — monoid might be integrally closed!")
        print(f"\n  Found {len(extra_vectors)} witness hole candidate(s)")

        holes_confirmed = 0
        for ev in extra_vectors:
            if not is_in_monoid_greedy(ev, self.letter_vectors, max_depth=50):
                holes_confirmed += 1
                print(f"  WITNESS HOLE confirmed: {ev}")

        self.assertGreater(holes_confirmed, 0,
                           "All extra HB vectors decompose — INCONCLUSIVE")
        print(f"  Total confirmed witness holes: {holes_confirmed}")
        print(f"  ⟹ integrally_closed = false PROVEN")


if __name__ == "__main__":
    unittest.main()
